"""Unit tests for cloud sink custom fields integration.

Generated file, do not edit.

This file is generated by the build system.
"""

from __future__ import annotations

from unittest.mock import MagicMock

import pytest

from jira_importer.config.config_models import CustomFieldConfig
from jira_importer.config.config_view import ConfigView
from jira_importer.import_pipeline.cloud.mappers import IssueMapper
from jira_importer.import_pipeline.cloud.metadata import MetadataCache
from jira_importer.import_pipeline.models import ColumnIndices, ProcessorResult
from jira_importer.import_pipeline.sinks.cloud_sink import _collect_issues_with_summaries, _separate_parent_child_issues


class TestCloudSinkCustomFields:
    """Tests for cloud sink custom fields integration."""

    @pytest.fixture
    def mapper(self) -> IssueMapper:
        """Create IssueMapper instance for testing."""
        cfg = ConfigView({})
        metadata = MetadataCache.__new__(MetadataCache)
        return IssueMapper(cfg, metadata)

    @pytest.fixture
    def result_with_custom_fields(self) -> ProcessorResult:
        """Create ProcessorResult with custom fields configured."""
        return ProcessorResult(
            header=["Priority", "Summary", "Project Key", "Issue Type", "CF Number"],
            rows=[["High", "Test Summary", "TEST", "Task", "42"]],
            indices=ColumnIndices(
                summary=1,
                project_key=2,
                issuetype=3,
                custom_fields={"customfield_10125": 4},
            ),
        )

    def test_collect_issues_with_custom_fields(
        self, mapper: IssueMapper, result_with_custom_fields: ProcessorResult
    ) -> None:
        """Test that _collect_issues_with_summaries includes custom fields in payload."""
        custom_configs_by_id: dict[str, CustomFieldConfig] = {
            "customfield_10125": CustomFieldConfig(name="CF Number", id="customfield_10125", type="number")
        }

        all_issues, summary_to_row = _collect_issues_with_summaries(
            result_with_custom_fields, mapper, custom_configs_by_id
        )

        assert len(all_issues) == 1
        row_index, payload, summary, row = all_issues[0]
        assert payload["fields"]["customfield_10125"] == 42
        assert summary == "Test Summary"
        assert payload["fields"]["project"] == {"key": "TEST"}
        assert payload["fields"]["issuetype"] == {"name": "Task"}

    def test_collect_issues_without_custom_configs(
        self, mapper: IssueMapper, result_with_custom_fields: ProcessorResult
    ) -> None:
        """Test that _collect_issues_with_summaries works without custom_configs_by_id."""
        all_issues, summary_to_row = _collect_issues_with_summaries(
            result_with_custom_fields, mapper, custom_configs_by_id=None
        )

        assert len(all_issues) == 1
        row_index, payload, summary, row = all_issues[0]
        # Custom fields should not be included when custom_configs_by_id is None
        assert "customfield_10125" not in payload["fields"]
        assert summary == "Test Summary"

    def test_separate_parent_child_issues_with_custom_fields(
        self, mapper: IssueMapper, result_with_custom_fields: ProcessorResult
    ) -> None:
        """Test that _separate_parent_child_issues passes custom_configs_by_id through."""
        custom_configs_by_id: dict[str, CustomFieldConfig] = {
            "customfield_10125": CustomFieldConfig(name="CF Number", id="customfield_10125", type="number")
        }

        config = MagicMock()
        epics, stories_and_tasks, sub_tasks, parent_mapping, all_issues = _separate_parent_child_issues(
            result_with_custom_fields, mapper, config, custom_configs_by_id
        )

        # Verify that custom fields are included in the payloads
        # (The actual separation logic is tested elsewhere, we just verify custom fields are passed through)
        assert all_issues is not None
