"""Unit tests for CSV sink, including custom field header transformation.

Generated file, do not edit.

This file is generated by the build system.
"""

from __future__ import annotations

from pathlib import Path
from tempfile import TemporaryDirectory

from jira_importer.import_pipeline.models import ColumnIndices, ProcessorResult
from jira_importer.import_pipeline.sinks.csv_sink import write_csv


class TestCsvSinkCustomFields:
    """Tests for CSV sink custom field header transformation."""

    def test_csv_header_transformation_with_custom_fields(self) -> None:
        """Test that custom field names are replaced with IDs in CSV header."""
        result = ProcessorResult(
            header=["Priority", "Summary", "CF Number", "CF Text"],
            rows=[["High", "Test", "42", "Value"]],
            indices=ColumnIndices(
                summary=1,
                custom_fields={"customfield_10125": 2, "customfield_10124": 3},
            ),
        )

        with TemporaryDirectory() as tmpdir:
            out_path = Path(tmpdir) / "output.csv"
            write_csv(result, out_path)

            # Read back and verify header
            with open(out_path, encoding="utf-8") as f:
                lines = f.readlines()
                header = lines[0].strip().split(",")
                assert "customfield_10125" in header
                assert "customfield_10124" in header
                assert "CF Number" not in header
                assert "CF Text" not in header

    def test_csv_header_no_transformation_without_custom_fields(self) -> None:
        """Test that header is unchanged when no custom fields are configured."""
        result = ProcessorResult(
            header=["Priority", "Summary", "CF Number"],
            rows=[["High", "Test", "42"]],
            indices=ColumnIndices(summary=1, custom_fields={}),
        )

        with TemporaryDirectory() as tmpdir:
            out_path = Path(tmpdir) / "output.csv"
            write_csv(result, out_path)

            # Read back and verify header unchanged
            with open(out_path, encoding="utf-8") as f:
                lines = f.readlines()
                header = lines[0].strip().split(",")
                assert "CF Number" in header
                assert "customfield_10125" not in header

    def test_csv_header_no_transformation_without_indices(self) -> None:
        """Test that header is unchanged when indices are None."""
        result = ProcessorResult(
            header=["Priority", "Summary", "CF Number"],
            rows=[["High", "Test", "42"]],
            indices=None,
        )

        with TemporaryDirectory() as tmpdir:
            out_path = Path(tmpdir) / "output.csv"
            write_csv(result, out_path)

            # Read back and verify header unchanged
            with open(out_path, encoding="utf-8") as f:
                lines = f.readlines()
                header = lines[0].strip().split(",")
                assert "CF Number" in header

    def test_csv_header_transformation_preserves_non_custom_fields(self) -> None:
        """Test that non-custom field headers are preserved."""
        result = ProcessorResult(
            header=["Priority", "Summary", "CF Number", "Description"],
            rows=[["High", "Test", "42", "Desc"]],
            indices=ColumnIndices(
                summary=1,
                custom_fields={"customfield_10125": 2},
            ),
        )

        with TemporaryDirectory() as tmpdir:
            out_path = Path(tmpdir) / "output.csv"
            write_csv(result, out_path)

            # Read back and verify
            with open(out_path, encoding="utf-8") as f:
                lines = f.readlines()
                header = lines[0].strip().split(",")
                assert "Priority" in header
                assert "Summary" in header
                assert "Description" in header
                assert "customfield_10125" in header
                assert "CF Number" not in header
