"""Unit tests for config models, including CustomFieldConfig and parse_teams.

Generated file, do not edit.

This file is generated by the build system.
"""

from __future__ import annotations

from pathlib import Path
from unittest.mock import MagicMock

import pytest

from jira_importer.config.config_models import (
    CustomFieldConfig,
    ExcelTableConfig,
    get_custom_field_configs,
    parse_custom_fields,
    parse_teams,
)
from jira_importer.config.config_view import ConfigView
from jira_importer.errors import ConfigurationError


class TestCustomFieldConfig:
    """Tests for CustomFieldConfig dataclass."""

    def test_custom_field_config_creation(self) -> None:
        """Test creating CustomFieldConfig with valid values."""
        cfg = CustomFieldConfig(name="CF Number", id="customfield_10125", type="number")
        assert cfg.name == "CF Number"
        assert cfg.id == "customfield_10125"
        assert cfg.type == "number"

    def test_custom_field_config_frozen(self) -> None:
        """Test that CustomFieldConfig is frozen (immutable)."""
        cfg = CustomFieldConfig(name="Test", id="customfield_123", type="text")
        with pytest.raises(Exception):  # dataclass frozen raises FrozenInstanceError
            cfg.name = "Changed"  # type: ignore[misc]


class TestParseCustomFields:
    """Tests for parse_custom_fields function."""

    def test_parse_empty_list(self) -> None:
        """Test parsing empty custom fields list."""
        cfg_view = ConfigView({"jira": {}})
        result = parse_custom_fields(cfg_view)
        assert result == []

    def test_parse_missing_key(self) -> None:
        """Test parsing when jira.custom_fields key is missing."""
        cfg_view = ConfigView({})
        result = parse_custom_fields(cfg_view)
        assert result == []

    def test_parse_valid_custom_fields(self) -> None:
        """Test parsing valid custom fields config."""
        cfg_view = ConfigView(
            {
                "jira": {
                    "custom_fields": [
                        {"name": "CF Number", "id": "customfield_10125", "type": "number"},
                        {"name": "CF Text", "id": "customfield_10124", "type": "text"},
                    ]
                }
            }
        )
        result = parse_custom_fields(cfg_view)
        assert len(result) == 2
        assert result[0].name == "CF Number"
        assert result[0].id == "customfield_10125"
        assert result[0].type == "number"
        assert result[1].name == "CF Text"
        assert result[1].id == "customfield_10124"
        assert result[1].type == "text"

    def test_parse_invalid_field_type(self) -> None:
        """Test parsing with invalid field type."""
        cfg_view = ConfigView(
            {"jira": {"custom_fields": [{"name": "CF Invalid", "id": "customfield_123", "type": "invalid"}]}}
        )
        with pytest.raises(ConfigurationError) as exc_info:
            parse_custom_fields(cfg_view)
        assert "Invalid custom field type" in str(exc_info.value)
        assert "invalid" in str(exc_info.value)

    def test_parse_missing_name(self) -> None:
        """Test parsing with missing name field."""
        cfg_view = ConfigView({"jira": {"custom_fields": [{"id": "customfield_123", "type": "text"}]}})
        with pytest.raises(ConfigurationError) as exc_info:
            parse_custom_fields(cfg_view)
        assert "missing 'name'" in str(exc_info.value)

    def test_parse_missing_id(self) -> None:
        """Test parsing with missing id field."""
        cfg_view = ConfigView({"jira": {"custom_fields": [{"name": "CF Test", "type": "text"}]}})
        with pytest.raises(ConfigurationError) as exc_info:
            parse_custom_fields(cfg_view)
        assert "missing 'id'" in str(exc_info.value)

    def test_parse_invalid_data_type(self) -> None:
        """Test parsing with invalid data type (not a dict)."""
        cfg_view = ConfigView({"jira": {"custom_fields": ["not-a-dict"]}})
        with pytest.raises(ConfigurationError) as exc_info:
            parse_custom_fields(cfg_view)
        assert "expected dict" in str(exc_info.value)

    def test_parse_duplicate_id(self) -> None:
        """Test parsing with duplicate field IDs."""
        cfg_view = ConfigView(
            {
                "jira": {
                    "custom_fields": [
                        {"name": "CF One", "id": "customfield_123", "type": "text"},
                        {"name": "CF Two", "id": "customfield_123", "type": "number"},
                    ]
                }
            }
        )
        with pytest.raises(ConfigurationError) as exc_info:
            parse_custom_fields(cfg_view)
        assert "Duplicate custom field id" in str(exc_info.value)
        assert "customfield_123" in str(exc_info.value)

    def test_parse_name_conflict(self) -> None:
        """Test parsing with same name but different IDs."""
        cfg_view = ConfigView(
            {
                "jira": {
                    "custom_fields": [
                        {"name": "CF Test", "id": "customfield_123", "type": "text"},
                        {"name": "CF Test", "id": "customfield_456", "type": "number"},
                    ]
                }
            }
        )
        with pytest.raises(ConfigurationError) as exc_info:
            parse_custom_fields(cfg_view)
        assert "defined for multiple field ids" in str(exc_info.value)
        assert "CF Test" in str(exc_info.value)

    def test_parse_name_case_insensitive_conflict(self) -> None:
        """Test parsing with same name (case-insensitive) but different IDs."""
        cfg_view = ConfigView(
            {
                "jira": {
                    "custom_fields": [
                        {"name": "CF Test", "id": "customfield_123", "type": "text"},
                        {"name": "cf test", "id": "customfield_456", "type": "number"},
                    ]
                }
            }
        )
        with pytest.raises(ConfigurationError) as exc_info:
            parse_custom_fields(cfg_view)
        assert "defined for multiple field ids" in str(exc_info.value)

    def test_parse_all_field_types(self) -> None:
        """Test parsing all supported field types."""
        cfg_view = ConfigView(
            {
                "jira": {
                    "custom_fields": [
                        {"name": "CF Text", "id": "customfield_1", "type": "text"},
                        {"name": "CF Number", "id": "customfield_2", "type": "number"},
                        {"name": "CF Date", "id": "customfield_3", "type": "date"},
                        {"name": "CF Select", "id": "customfield_4", "type": "select"},
                        {"name": "CF Any", "id": "customfield_5", "type": "any"},
                    ]
                }
            }
        )
        result = parse_custom_fields(cfg_view)
        assert len(result) == 5
        assert {cfg.type for cfg in result} == {"text", "number", "date", "select", "any"}

    def test_parse_strips_whitespace(self) -> None:
        """Test that parsing strips whitespace from values."""
        cfg_view = ConfigView(
            {"jira": {"custom_fields": [{"name": "  CF Test  ", "id": "  customfield_123  ", "type": "  text  "}]}}
        )
        result = parse_custom_fields(cfg_view)
        assert len(result) == 1
        assert result[0].name == "CF Test"
        assert result[0].id == "customfield_123"
        assert result[0].type == "text"


class TestParseTeams:
    """Tests for parse_teams function."""

    def test_parse_empty_list(self) -> None:
        """Test parsing empty teams list."""
        cfg_view = ConfigView({"jira": {}})
        result = parse_teams(cfg_view)
        assert result == []

    def test_parse_missing_key(self) -> None:
        """Test parsing when jira.teams key is missing."""
        cfg_view = ConfigView({})
        result = parse_teams(cfg_view)
        assert result == []

    def test_parse_valid_teams(self) -> None:
        """Test parsing valid teams config."""
        cfg_view = ConfigView(
            {
                "jira": {
                    "teams": [
                        {"name": "Backend", "id": "12345"},
                        {"name": "Frontend", "id": "67890"},
                    ]
                }
            }
        )
        result = parse_teams(cfg_view)
        assert len(result) == 2
        assert result[0].name == "Backend"
        assert result[0].id == "12345"
        assert result[1].name == "Frontend"
        assert result[1].id == "67890"

    def test_parse_missing_name(self) -> None:
        """Test parsing with missing name field."""
        cfg_view = ConfigView({"jira": {"teams": [{"id": "12345"}]}})
        with pytest.raises(ConfigurationError) as exc_info:
            parse_teams(cfg_view)
        assert "missing 'name'" in str(exc_info.value)

    def test_parse_missing_id(self) -> None:
        """Test parsing with missing id field."""
        cfg_view = ConfigView({"jira": {"teams": [{"name": "Backend"}]}})
        with pytest.raises(ConfigurationError) as exc_info:
            parse_teams(cfg_view)
        assert "missing 'id'" in str(exc_info.value)

    def test_parse_empty_name_after_strip(self) -> None:
        """Test parsing with empty name after strip."""
        cfg_view = ConfigView({"jira": {"teams": [{"name": "  ", "id": "12345"}]}})
        with pytest.raises(ConfigurationError) as exc_info:
            parse_teams(cfg_view)
        assert "missing 'name'" in str(exc_info.value)

    def test_parse_empty_id_after_strip(self) -> None:
        """Test parsing with empty id after strip."""
        cfg_view = ConfigView({"jira": {"teams": [{"name": "Backend", "id": ""}]}})
        with pytest.raises(ConfigurationError) as exc_info:
            parse_teams(cfg_view)
        assert "missing 'id'" in str(exc_info.value)

    def test_parse_invalid_data_type(self) -> None:
        """Test parsing with invalid data type (not a dict)."""
        cfg_view = ConfigView({"jira": {"teams": ["not-a-dict"]}})
        with pytest.raises(ConfigurationError) as exc_info:
            parse_teams(cfg_view)
        assert "expected dict" in str(exc_info.value)

    def test_parse_duplicate_id(self) -> None:
        """Test parsing with duplicate team IDs."""
        cfg_view = ConfigView(
            {
                "jira": {
                    "teams": [
                        {"name": "Team One", "id": "12345"},
                        {"name": "Team Two", "id": "12345"},
                    ]
                }
            }
        )
        with pytest.raises(ConfigurationError) as exc_info:
            parse_teams(cfg_view)
        assert "Duplicate" in str(exc_info.value)
        assert "12345" in str(exc_info.value)

    def test_parse_duplicate_name_normalized(self) -> None:
        """Test parsing with same name (case-insensitive) but different IDs."""
        cfg_view = ConfigView(
            {
                "jira": {
                    "teams": [
                        {"name": "Backend", "id": "12345"},
                        {"name": "backend", "id": "67890"},
                    ]
                }
            }
        )
        with pytest.raises(ConfigurationError) as exc_info:
            parse_teams(cfg_view)
        assert "multiple" in str(exc_info.value).lower() or "Duplicate" in str(exc_info.value)
        assert "Backend" in str(exc_info.value) or "backend" in str(exc_info.value)

    def test_parse_strips_whitespace(self) -> None:
        """Test that parsing strips whitespace from name and id."""
        cfg_view = ConfigView({"jira": {"teams": [{"name": "  Backend  ", "id": "  12345  "}]}})
        result = parse_teams(cfg_view)
        assert len(result) == 1
        assert result[0].name == "Backend"
        assert result[0].id == "12345"

    def test_parse_accepts_plain_dict(self) -> None:
        """Test that parse_teams accepts a plain dict (wraps in ConfigView)."""
        result = parse_teams({"jira": {"teams": [{"name": "Team", "id": "1"}]}})
        assert len(result) == 1
        assert result[0].name == "Team"
        assert result[0].id == "1"


class TestJsonConfigurationGetTableConfig:
    """Tests for JsonConfiguration.get_table_config() with jira.teams."""

    def test_get_table_config_returns_excel_table_config_with_teams(self, tmp_path: Path) -> None:
        """get_table_config() returns ExcelTableConfig with teams from jira.teams."""
        from jira_importer.config.json_config import JsonConfiguration

        config_path = tmp_path / "config.json"
        config_path.write_text(
            '{"metadata":{"version":7},"jira":{"teams":[{"name":"Backend","id":"12345"},'
            '{"name":"Frontend","id":"67890"}]}}',
            encoding="utf-8",
        )
        config = JsonConfiguration(path=str(config_path))
        table_config = config.get_table_config()
        assert table_config is not None
        assert len(table_config.teams) == 2
        assert table_config.get_team_by_name("Backend") is not None
        assert table_config.get_team_by_name("Backend").id == "12345"
        assert table_config.get_team_by_id("67890") is not None
        assert table_config.get_team_by_id("67890").name == "Frontend"

    def test_get_table_config_empty_teams_when_jira_teams_missing(self, tmp_path: Path) -> None:
        """get_table_config() returns ExcelTableConfig with empty teams when jira.teams missing."""
        from jira_importer.config.json_config import JsonConfiguration

        config_path = tmp_path / "config.json"
        config_path.write_text(
            '{"metadata":{"version":7},"jira":{}}',
            encoding="utf-8",
        )
        config = JsonConfiguration(path=str(config_path))
        table_config = config.get_table_config()
        assert table_config is not None
        assert table_config.teams == []

    def test_get_table_config_cached(self, tmp_path: Path) -> None:
        """get_table_config() returns the same instance on subsequent calls."""
        from jira_importer.config.json_config import JsonConfiguration

        config_path = tmp_path / "config.json"
        config_path.write_text(
            '{"metadata":{"version":7},"jira":{"teams":[{"name":"A","id":"1"}]}}',
            encoding="utf-8",
        )
        config = JsonConfiguration(path=str(config_path))
        first = config.get_table_config()
        second = config.get_table_config()
        assert first is second


class TestGetCustomFieldConfigs:
    """Tests for get_custom_field_configs function."""

    def test_get_from_json_config(self) -> None:
        """Test getting custom fields from JsonConfiguration (via parse_custom_fields)."""
        # Mock a non-Excel config (any object that's not ExcelConfiguration)
        json_config = MagicMock()
        # get_custom_field_configs will use isinstance check, so we need to make it fail
        # and fall through to parse_custom_fields path

        cfg_view = ConfigView(
            {"jira": {"custom_fields": [{"name": "CF Test", "id": "customfield_123", "type": "text"}]}}
        )
        result = get_custom_field_configs(json_config, cfg_view)
        assert len(result) == 1
        assert result[0].name == "CF Test"
        assert result[0].id == "customfield_123"

    def test_get_from_excel_config_with_table_config(self) -> None:
        """Test getting custom fields from ExcelConfiguration with table_config."""
        from jira_importer.config.excel_config import ExcelConfiguration

        excel_config = MagicMock(spec=ExcelConfiguration)
        excel_config.table_config = ExcelTableConfig(
            custom_fields=[CustomFieldConfig(name="CF Excel", id="customfield_456", type="number")]
        )
        excel_config.get_table_config.return_value = excel_config.table_config

        cfg_view = ConfigView({})
        result = get_custom_field_configs(excel_config, cfg_view)
        assert len(result) == 1
        assert result[0].name == "CF Excel"
        assert result[0].id == "customfield_456"

    def test_get_from_excel_config_loads_table_config(self) -> None:
        """Test that get_custom_field_configs loads table config if not already loaded."""
        from jira_importer.config.excel_config import ExcelConfiguration

        excel_config = MagicMock(spec=ExcelConfiguration)
        excel_config.table_config = None
        excel_config.load_table_config.return_value = ExcelTableConfig(
            custom_fields=[CustomFieldConfig(name="CF Excel", id="customfield_456", type="number")]
        )
        excel_config.get_table_config.return_value = excel_config.load_table_config.return_value

        cfg_view = ConfigView({})
        result = get_custom_field_configs(excel_config, cfg_view)
        assert len(result) == 1
        excel_config.load_table_config.assert_called_once()

    def test_get_from_excel_config_load_failure_returns_empty(self) -> None:
        """Test that get_custom_field_configs returns empty list if table config load fails."""
        from jira_importer.config.excel_config import ExcelConfiguration

        excel_config = MagicMock(spec=ExcelConfiguration)
        excel_config.table_config = None
        excel_config.load_table_config.side_effect = Exception("Workbook not initialized")

        cfg_view = ConfigView({})
        result = get_custom_field_configs(excel_config, cfg_view)
        assert result == []

    def test_get_from_excel_config_no_table_config(self) -> None:
        """Test getting custom fields from ExcelConfiguration without table_config."""
        from jira_importer.config.excel_config import ExcelConfiguration

        excel_config = MagicMock(spec=ExcelConfiguration)
        excel_config.table_config = None
        excel_config.get_table_config.return_value = None

        cfg_view = ConfigView({})
        result = get_custom_field_configs(excel_config, cfg_view)
        assert result == []

    def test_get_from_excel_config_empty_custom_fields(self) -> None:
        """Test getting custom fields from ExcelConfiguration with empty custom_fields."""
        from jira_importer.config.excel_config import ExcelConfiguration

        excel_config = MagicMock(spec=ExcelConfiguration)
        excel_config.table_config = ExcelTableConfig(custom_fields=[])
        excel_config.get_table_config.return_value = excel_config.table_config

        cfg_view = ConfigView({})
        result = get_custom_field_configs(excel_config, cfg_view)
        assert result == []

    def test_single_source_selection_excel_wins(self) -> None:
        """Test that Excel config is used when both Excel and JSON have custom fields."""
        from jira_importer.config.excel_config import ExcelConfiguration

        # Excel config with custom fields
        excel_config = MagicMock(spec=ExcelConfiguration)
        excel_config.table_config = ExcelTableConfig(
            custom_fields=[CustomFieldConfig(name="CF Excel", id="customfield_456", type="number")]
        )
        excel_config.get_table_config.return_value = excel_config.table_config

        # JSON config view also has custom fields (should be ignored)
        cfg_view = ConfigView(
            {"jira": {"custom_fields": [{"name": "CF JSON", "id": "customfield_789", "type": "text"}]}}
        )

        result = get_custom_field_configs(excel_config, cfg_view)
        # Should return Excel configs only
        assert len(result) == 1
        assert result[0].name == "CF Excel"
        assert result[0].id == "customfield_456"
