"""Unit tests for IssueMapper, including custom field transformation.

Generated file, do not edit.

This file is generated by the build system.
"""

from __future__ import annotations

from datetime import date, datetime
from typing import Any

import pytest

from jira_importer.config.config_models import CustomFieldConfig
from jira_importer.config.config_view import ConfigView
from jira_importer.errors import ConfigurationError, RowProcessingError
from jira_importer.import_pipeline.cloud.mappers import IssueMapper
from jira_importer.import_pipeline.cloud.metadata import MetadataCache
from jira_importer.import_pipeline.models import ColumnIndices


class TestTransformCustomValue:
    """Tests for _transform_custom_value method."""

    @pytest.fixture
    def mapper(self) -> IssueMapper:
        """Create IssueMapper instance for testing."""
        cfg = ConfigView({})
        metadata = MetadataCache.__new__(MetadataCache)
        return IssueMapper(cfg, metadata)

    def test_transform_text_value(self, mapper: IssueMapper) -> None:
        """Test transforming text field value."""
        cfg = CustomFieldConfig(name="CF Text", id="customfield_123", type="text")
        result = mapper._transform_custom_value("  Test Value  ", cfg)  # pylint: disable=protected-access
        assert result == "Test Value"

    def test_transform_text_none(self, mapper: IssueMapper) -> None:
        """Test transforming text field with None value."""
        cfg = CustomFieldConfig(name="CF Text", id="customfield_123", type="text")
        result = mapper._transform_custom_value(None, cfg)
        assert result is None

    def test_transform_text_empty_string(self, mapper: IssueMapper) -> None:
        """Test transforming text field with empty string."""
        cfg = CustomFieldConfig(name="CF Text", id="customfield_123", type="text")
        result = mapper._transform_custom_value("", cfg)
        assert result is None

    def test_transform_text_whitespace_only(self, mapper: IssueMapper) -> None:
        """Test transforming text field with whitespace-only string."""
        cfg = CustomFieldConfig(name="CF Text", id="customfield_123", type="text")
        result = mapper._transform_custom_value("   ", cfg)
        assert result is None

    def test_transform_number_int(self, mapper: IssueMapper) -> None:
        """Test transforming number field with integer value."""
        cfg = CustomFieldConfig(name="CF Number", id="customfield_123", type="number")
        result = mapper._transform_custom_value("42", cfg)
        assert result == 42
        assert isinstance(result, int)

    def test_transform_number_float(self, mapper: IssueMapper) -> None:
        """Test transforming number field with float value."""
        cfg = CustomFieldConfig(name="CF Number", id="customfield_123", type="number")
        result = mapper._transform_custom_value("3.14", cfg)
        assert result == 3.14
        assert isinstance(result, float)

    def test_transform_number_scientific_notation(self, mapper: IssueMapper) -> None:
        """Test transforming number field with scientific notation."""
        cfg = CustomFieldConfig(name="CF Number", id="customfield_123", type="number")
        result = mapper._transform_custom_value("1.5e2", cfg)
        assert result == 150.0
        assert isinstance(result, float)

    def test_transform_number_invalid(self, mapper: IssueMapper) -> None:
        """Test transforming number field with invalid value."""
        cfg = CustomFieldConfig(name="CF Number", id="customfield_123", type="number")
        with pytest.raises(RowProcessingError) as exc_info:
            mapper._transform_custom_value("not-a-number", cfg)
        assert "Invalid number value" in str(exc_info.value)
        assert "CF Number" in str(exc_info.value)
        assert "customfield_123" in str(exc_info.value)

    def test_transform_date_datetime_object(self, mapper: IssueMapper) -> None:
        """Test transforming date field with datetime object."""
        cfg = CustomFieldConfig(name="CF Date", id="customfield_123", type="date")
        dt = datetime(2024, 1, 15, 14, 30, 0)
        result = mapper._transform_custom_value(dt, cfg)
        assert result == "2024-01-15"

    def test_transform_date_date_object(self, mapper: IssueMapper) -> None:
        """Test transforming date field with date object."""
        cfg = CustomFieldConfig(name="CF Date", id="customfield_123", type="date")
        d = date(2024, 1, 15)
        result = mapper._transform_custom_value(d, cfg)
        assert result == "2024-01-15"

    def test_transform_date_string_iso_format(self, mapper: IssueMapper) -> None:
        """Test transforming date field with ISO format string."""
        cfg = CustomFieldConfig(name="CF Date", id="customfield_123", type="date")
        result = mapper._transform_custom_value("2024-01-15", cfg)
        assert result == "2024-01-15"

    def test_transform_date_string_us_format(self, mapper: IssueMapper) -> None:
        """Test transforming date field with US format string."""
        cfg = CustomFieldConfig(name="CF Date", id="customfield_123", type="date")
        result = mapper._transform_custom_value("01/15/2024", cfg)
        assert result == "2024-01-15"

    def test_transform_date_string_eu_format(self, mapper: IssueMapper) -> None:
        """Test transforming date field with EU format string."""
        cfg = CustomFieldConfig(name="CF Date", id="customfield_123", type="date")
        result = mapper._transform_custom_value("15/01/2024", cfg)
        assert result == "2024-01-15"

    def test_transform_date_string_with_time(self, mapper: IssueMapper) -> None:
        """Test transforming date field with datetime string."""
        cfg = CustomFieldConfig(name="CF Date", id="customfield_123", type="date")
        result = mapper._transform_custom_value("2024-01-15 14:30:00", cfg)
        assert result == "2024-01-15"

    def test_transform_date_numeric_rejected(self, mapper: IssueMapper) -> None:
        """Test transforming date field with numeric value (rejected in MVP)."""
        cfg = CustomFieldConfig(name="CF Date", id="customfield_123", type="date")
        with pytest.raises(RowProcessingError) as exc_info:
            mapper._transform_custom_value(45285, cfg)  # Excel serial date
        assert "Numeric Excel date values are not supported" in str(exc_info.value)
        assert "CF Date" in str(exc_info.value)
        assert "customfield_123" in str(exc_info.value)

    def test_transform_date_float_rejected(self, mapper: IssueMapper) -> None:
        """Test transforming date field with float value (rejected in MVP)."""
        cfg = CustomFieldConfig(name="CF Date", id="customfield_123", type="date")
        with pytest.raises(RowProcessingError) as exc_info:
            mapper._transform_custom_value(45285.5, cfg)
        assert "Numeric Excel date values are not supported" in str(exc_info.value)

    def test_transform_date_invalid_string(self, mapper: IssueMapper) -> None:
        """Test transforming date field with invalid string format."""
        cfg = CustomFieldConfig(name="CF Date", id="customfield_123", type="date")
        with pytest.raises(RowProcessingError) as exc_info:
            mapper._transform_custom_value("invalid-date", cfg)
        assert "Invalid date value" in str(exc_info.value)
        assert "Expected format" in str(exc_info.value)

    def test_transform_date_unsupported_type(self, mapper: IssueMapper) -> None:
        """Test transforming date field with unsupported type."""
        cfg = CustomFieldConfig(name="CF Date", id="customfield_123", type="date")
        with pytest.raises(RowProcessingError) as exc_info:
            mapper._transform_custom_value(["list"], cfg)
        assert "Unsupported value type" in str(exc_info.value)
        assert "list" in str(exc_info.value)

    def test_transform_select_value(self, mapper: IssueMapper) -> None:
        """Test transforming select field value."""
        cfg = CustomFieldConfig(name="CF Select", id="customfield_123", type="select")
        result = mapper._transform_custom_value("Option A", cfg)
        assert result == {"value": "Option A"}

    def test_transform_select_trimmed(self, mapper: IssueMapper) -> None:
        """Test transforming select field value with whitespace."""
        cfg = CustomFieldConfig(name="CF Select", id="customfield_123", type="select")
        result = mapper._transform_custom_value("  Option A  ", cfg)
        assert result == {"value": "Option A"}

    def test_transform_unsupported_type(self, mapper: IssueMapper) -> None:
        """Test transforming with unsupported field type."""
        # Create a config with invalid type (bypassing type checking)
        cfg = CustomFieldConfig(name="CF Invalid", id="customfield_123", type="invalid")  # type: ignore[arg-type]
        with pytest.raises(ConfigurationError) as exc_info:
            mapper._transform_custom_value("test", cfg)
        assert "Unsupported custom field type" in str(exc_info.value)
        assert "invalid" in str(exc_info.value)

    def test_transform_error_context(self, mapper: IssueMapper) -> None:
        """Test that error includes proper context."""
        cfg = CustomFieldConfig(name="CF Number", id="customfield_123", type="number")
        with pytest.raises(RowProcessingError) as exc_info:
            mapper._transform_custom_value("invalid", cfg)
        error = exc_info.value
        assert error.details is not None
        assert error.details["field_name"] == "CF Number"
        assert error.details["field_id"] == "customfield_123"
        assert error.details["field_type"] == "number"
        assert error.details["raw_value"] == "invalid"
        assert "raw_type" in error.details


class TestMapCustomFields:
    """Tests for _map_custom_fields method."""

    @pytest.fixture
    def mapper(self) -> IssueMapper:
        """Create IssueMapper instance for testing."""
        cfg = ConfigView({})
        metadata = MetadataCache.__new__(MetadataCache)
        return IssueMapper(cfg, metadata)

    def test_map_custom_fields_single_field(self, mapper: IssueMapper) -> None:
        """Test mapping a single custom field."""
        fields: dict[str, Any] = {}
        row = ["Summary", "Value1"]
        indices = ColumnIndices(
            summary=0,
            custom_fields={"customfield_123": 1},
        )
        custom_configs_by_id: dict[str, CustomFieldConfig] = {
            "customfield_123": CustomFieldConfig(name="CF Text", id="customfield_123", type="text")
        }

        mapper._map_custom_fields(fields, row, indices, custom_configs_by_id)  # pylint: disable=protected-access  # pylint: disable=protected-access
        assert fields["customfield_123"] == "Value1"

    def test_map_custom_fields_multiple_fields(self, mapper: IssueMapper) -> None:
        """Test mapping multiple custom fields."""
        fields: dict[str, Any] = {}
        row = ["Summary", "Text Value", 42, "2024-01-15", "Option A"]
        indices = ColumnIndices(
            summary=0,
            custom_fields={
                "customfield_1": 1,
                "customfield_2": 2,
                "customfield_3": 3,
                "customfield_4": 4,
            },
        )
        custom_configs_by_id: dict[str, CustomFieldConfig] = {
            "customfield_1": CustomFieldConfig(name="CF Text", id="customfield_1", type="text"),
            "customfield_2": CustomFieldConfig(name="CF Number", id="customfield_2", type="number"),
            "customfield_3": CustomFieldConfig(name="CF Date", id="customfield_3", type="date"),
            "customfield_4": CustomFieldConfig(name="CF Select", id="customfield_4", type="select"),
        }

        mapper._map_custom_fields(fields, row, indices, custom_configs_by_id)  # pylint: disable=protected-access
        assert fields["customfield_1"] == "Text Value"
        assert fields["customfield_2"] == 42
        assert fields["customfield_3"] == "2024-01-15"
        assert fields["customfield_4"] == {"value": "Option A"}

    def test_map_custom_fields_missing_config(self, mapper: IssueMapper) -> None:
        """Test mapping when config is missing (logs warning, continues)."""
        fields: dict[str, Any] = {}
        row = ["Summary", "Value1"]
        indices = ColumnIndices(
            summary=0,
            custom_fields={"customfield_123": 1},
        )
        custom_configs_by_id: dict[str, CustomFieldConfig] = {}  # Missing config

        # Should not raise, just log warning
        mapper._map_custom_fields(fields, row, indices, custom_configs_by_id)  # pylint: disable=protected-access
        assert "customfield_123" not in fields

    def test_map_custom_fields_empty_value(self, mapper: IssueMapper) -> None:
        """Test mapping custom field with empty value (not added to fields)."""
        fields: dict[str, Any] = {}
        row = ["Summary", ""]
        indices = ColumnIndices(
            summary=0,
            custom_fields={"customfield_123": 1},
        )
        custom_configs_by_id: dict[str, CustomFieldConfig] = {
            "customfield_123": CustomFieldConfig(name="CF Text", id="customfield_123", type="text")
        }

        mapper._map_custom_fields(fields, row, indices, custom_configs_by_id)  # pylint: disable=protected-access
        assert "customfield_123" not in fields

    def test_map_custom_fields_invalid_value_raises(self, mapper: IssueMapper) -> None:
        """Test mapping custom field with invalid value raises RowProcessingError."""
        fields: dict[str, Any] = {}
        row = ["Summary", "not-a-number"]
        indices = ColumnIndices(
            summary=0,
            custom_fields={"customfield_123": 1},
        )
        custom_configs_by_id = {
            "customfield_123": CustomFieldConfig(name="CF Number", id="customfield_123", type="number")
        }

        with pytest.raises(RowProcessingError) as exc_info:
            mapper._map_custom_fields(fields, row, indices, custom_configs_by_id)  # pylint: disable=protected-access
        assert "Invalid number value" in str(exc_info.value)
        assert "CF Number" in str(exc_info.value)

    def test_map_custom_fields_out_of_bounds_index(self, mapper: IssueMapper) -> None:
        """Test mapping when column index is out of bounds."""
        fields: dict[str, Any] = {}
        row = ["Summary"]  # Only one column
        indices = ColumnIndices(
            summary=0,
            custom_fields={"customfield_123": 5},  # Index 5 doesn't exist
        )
        custom_configs_by_id: dict[str, CustomFieldConfig] = {
            "customfield_123": CustomFieldConfig(name="CF Text", id="customfield_123", type="text")
        }

        # Should not raise, just skip
        mapper._map_custom_fields(fields, row, indices, custom_configs_by_id)  # pylint: disable=protected-access
        assert "customfield_123" not in fields
