"""Unit tests for ImportProcessor custom fields integration.

Generated file, do not edit.

This file is generated by the build system.
"""

from __future__ import annotations

from unittest.mock import MagicMock, patch

import pytest

from jira_importer.config.config_models import CustomFieldConfig
from jira_importer.import_pipeline.models import HeaderSchema
from jira_importer.import_pipeline.processor import ImportProcessor


class TestProcessorCustomFields:
    """Tests for ImportProcessor custom fields extraction."""

    @pytest.fixture
    def processor(self) -> ImportProcessor:
        """Create ImportProcessor instance for testing."""
        config = MagicMock()
        ui = MagicMock()
        return ImportProcessor(
            path=MagicMock(),
            config=config,
            ui=ui,
            enable_excel_rules=False,
            enable_auto_fix=False,
        )

    def test_extract_indices_matches_custom_fields(self, processor: ImportProcessor) -> None:
        """Test that custom fields are matched to Excel headers."""
        header = HeaderSchema(
            original=["Priority", "Summary", "CF Number", "CF Text"],
            normalized=["Priority", "Summary", "CF Number", "CF Text"],
        )

        custom_configs = [
            CustomFieldConfig(name="CF Number", id="customfield_10125", type="number"),
            CustomFieldConfig(name="CF Text", id="customfield_10124", type="text"),
        ]

        with patch("jira_importer.import_pipeline.processor.get_custom_field_configs", return_value=custom_configs):
            indices = processor._extract_indices(header)  # pylint: disable=protected-access

            assert indices.custom_fields["customfield_10125"] == 2
            assert indices.custom_fields["customfield_10124"] == 3

    def test_extract_indices_case_insensitive_matching(self, processor: ImportProcessor) -> None:
        """Test that custom field matching is case-insensitive."""
        header = HeaderSchema(
            original=["Priority", "Summary", "cf number"],
            normalized=["Priority", "Summary", "cf number"],
        )

        custom_configs = [
            CustomFieldConfig(name="CF Number", id="customfield_10125", type="number"),
        ]

        with patch("jira_importer.import_pipeline.processor.get_custom_field_configs", return_value=custom_configs):
            indices = processor._extract_indices(header)  # pylint: disable=protected-access

            assert indices.custom_fields["customfield_10125"] == 2

    def test_extract_indices_no_match_warns(self, processor: ImportProcessor) -> None:
        """Test that unmatched custom fields log a warning."""
        header = HeaderSchema(
            original=["Priority", "Summary"],
            normalized=["Priority", "Summary"],
        )

        custom_configs = [
            CustomFieldConfig(name="CF Missing", id="customfield_10125", type="number"),
        ]

        with patch("jira_importer.import_pipeline.processor.get_custom_field_configs", return_value=custom_configs):
            with patch("jira_importer.import_pipeline.processor.logger") as mock_logger:
                indices = processor._extract_indices(header)  # pylint: disable=protected-access

                assert len(indices.custom_fields) == 0
                mock_logger.warning.assert_called_once()
                assert "CF Missing" in str(mock_logger.warning.call_args)

    def test_extract_indices_no_custom_fields_config(self, processor: ImportProcessor) -> None:
        """Test that processor handles missing custom fields config gracefully."""
        header = HeaderSchema(
            original=["Priority", "Summary"],
            normalized=["Priority", "Summary"],
        )

        with patch("jira_importer.import_pipeline.processor.get_custom_field_configs", return_value=[]):
            indices = processor._extract_indices(header)  # pylint: disable=protected-access

            assert len(indices.custom_fields) == 0

    def test_extract_indices_whitespace_normalization(self, processor: ImportProcessor) -> None:
        """Test that header and config names are normalized (trimmed, lowercased) for matching."""
        header = HeaderSchema(
            original=["Priority", "Summary", "  CF Number  "],
            normalized=["Priority", "Summary", "  CF Number  "],
        )

        custom_configs = [
            CustomFieldConfig(name="  CF Number  ", id="customfield_10125", type="number"),
        ]

        with patch("jira_importer.import_pipeline.processor.get_custom_field_configs", return_value=custom_configs):
            indices = processor._extract_indices(header)  # pylint: disable=protected-access

            assert indices.custom_fields["customfield_10125"] == 2
